services:
  app:
    image: space.fwix:5000/prophezeiung:latest
    pull_policy: always
    depends_on:
      db:
        condition: service_healthy
    container_name: prophezeiung-app
    ports:
      - '30055:3000'
    environment:
      DATABASE_URL: postgresql://prophezeiung:prophezeiung_dev@db:5432/prophezeiung
      NODE_ENV: production
      WEBAUTHN_RP_ID: prophecy.12-of-spades.com
      WEBAUTHN_ORIGIN: https://prophecy.12-of-spades.com
    volumes:
      - /mnt/Master/Apps/Prophecy/upload:/app/uploads
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: prophezeiung-db
    environment:
      POSTGRES_USER: prophezeiung
      POSTGRES_PASSWORD: prophezeiung_dev
      POSTGRES_DB: prophezeiung
    expose:
      - 5432
    volumes:
      - /mnt/Master/Apps/Prophecy/db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U prophezeiung']
      interval: 5s
      timeout: 5s
      retries: 5
